<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invalidReferenceMessage</name>
   <tag></tag>
   <elementGuidId>94d8dbb5-c8d6-4c0b-8ef7-8234adb86aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[2]/div/div[2]/div/section/form/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div[4]/div/div[2]/div/div[2]/div/section/form/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
