<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continuePaymentBtn</name>
   <tag></tag>
   <elementGuidId>7d2af2cd-af59-4739-b10c-b1b980566ab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-continue-to-payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-continue-to-payment</value>
   </webElementProperties>
</WebElementEntity>
