<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyEmailBtn</name>
   <tag></tag>
   <elementGuidId>194c2d1c-cbf5-4819-940a-a8d5530b02f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-email-password-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-email-password-button</value>
   </webElementProperties>
</WebElementEntity>
