<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>guestDetailsNextBtn</name>
   <tag></tag>
   <elementGuidId>84734710-132c-4a70-bfb7-e75c3cbac865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-guest-personal-details-next-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-guest-personal-details-next-button</value>
   </webElementProperties>
</WebElementEntity>
