<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signOut</name>
   <tag></tag>
   <elementGuidId>f4ce1334-f354-4ccf-bf8a-cff92bee6a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[1]/header/div[1]/ul/li[2]/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div[4]/div/div[1]/header/div[1]/ul/li[2]/div/div/ul/li[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
