<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addressNextBtn</name>
   <tag></tag>
   <elementGuidId>ba617d3d-fbba-4715-96cc-5d666ab105da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-address-next-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-address-next-button</value>
   </webElementProperties>
</WebElementEntity>
