<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectLodgeRadioBtn</name>
   <tag></tag>
   <elementGuidId>044b51ec-4f82-4aa0-b52a-6b4cea9816d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-select-lodge-radio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-select-lodge-radio</value>
   </webElementProperties>
</WebElementEntity>
