<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bookingOverview</name>
   <tag></tag>
   <elementGuidId>2f97f48b-4f74-417a-b6de-3a1d598b6b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;subnav__mybookings&quot;]/div/ul[1]/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;subnav__mybookings&quot;]/div/ul[1]/li[1]/a</value>
   </webElementXpaths>
</WebElementEntity>
