<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myBookingOverviewMessage</name>
   <tag></tag>
   <elementGuidId>11b977f8-c986-4e38-9a31-a7d7dfd484df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[2]/div/main/div/div[1]/div/div[1]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div[4]/div/div[2]/div/main/div/div[1]/div/div[1]/h1</value>
   </webElementXpaths>
</WebElementEntity>
