<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueBtn</name>
   <tag></tag>
   <elementGuidId>e390ab03-a082-4222-ac14-f6e21a9b9c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.js-proceed-to-payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.js-proceed-to-payment</value>
   </webElementProperties>
</WebElementEntity>
