<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editDetailsBtn</name>
   <tag></tag>
   <elementGuidId>4000c124-29ea-44a9-a179-b821fbfe1f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div[2]/div/form/div[2]/div/div/fieldset[2]/label/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div[4]/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div[2]/div/form/div[2]/div/div/fieldset[2]/label/a</value>
   </webElementXpaths>
</WebElementEntity>
