<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myDetailsHeader</name>
   <tag></tag>
   <elementGuidId>bc1ec301-5017-42d1-a7d9-3c0bc222f92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div[1]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/body/div[4]/div/div[2]/div/div[2]/div/div[1]/div/div[1]/div/div[1]/h1</value>
   </webElementXpaths>
</WebElementEntity>
